[Variables]

██╗░░░██╗░█████╗░██████╗░██╗░█████╗░██████╗░██╗░░░░░███████╗░██████╗
██║░░░██║██╔══██╗██╔══██╗██║██╔══██╗██╔══██╗██║░░░░░██╔════╝██╔════╝
╚██╗░██╔╝███████║██████╔╝██║███████║██████╦╝██║░░░░░█████╗░░╚█████╗░
░╚████╔╝░██╔══██║██╔══██╗██║██╔══██║██╔══██╗██║░░░░░██╔══╝░░░╚═══██╗
░░╚██╔╝░░██║░░██║██║░░██║██║██║░░██║██████╦╝███████╗███████╗██████╔╝
░░░╚═╝░░░╚═╝░░╚═╝╚═╝░░╚═╝╚═╝╚═╝░░╚═╝╚═════╝░╚══════╝╚══════╝╚═════╝░



;█▀▀ █░░ █▀█ █▀▀ █▄▀   █▀ █▀▀ ▀█▀ ▀█▀ █ █▄░█ █▀▀ █▀
;█▄▄ █▄▄ █▄█ █▄▄ █░█   ▄█ ██▄ ░█░ ░█░ █ █░▀█ █▄█ ▄█

CScale=1.5
Format=I
# 'H' for 24 hr Clock and 'I' for 12 hr clock
Hidden=1
# put '0' for 24 hr clock and '1' for 12 hr clock
Hidden2=0
# put '1' for 24 hr clock and '0' for 12 hr clock
Color1=255,255,255



;█▀▄ █▀█ █▀▀ █▄▀   █▀ █▀▀ ▀█▀ ▀█▀ █ █▄░█ █▀▀ █▀
;█▄▀ █▄█ █▄▄ █░█   ▄█ ██▄ ░█░ ░█░ █ █░▀█ █▄█ ▄█

DkScale=1.2
DkIconColor=255,255,255
DkHoverIconColor=255,255,255
DkHoverTextColor=255,255,255

Icon1NameAndPath=#@#Images\1.png
LocationPath1=Explorer Shell:::{20D04FE0-3AEA-1069-A2D8-08002B30309D}
Text1=My Computer

Icon2NameAndPath=#@#Images\8.png
LocationPath2=shutdown.exe /s /t 0
Text2=Shutdown

Icon3NameAndPath=#@#Images\9.png
LocationPath3=rundll32.exe powrprof.dll,SetSuspendState 0,1,0
Text3=Sleep

Icon4NameAndPath=#@#Images\4.png
LocationPath4=!Execute [chrome.exe]
Text4=Chrome

Icon5NameAndPath=#@#Images\7.png
LocationPath5=!Execute ["#@#\Application\Music"]
Text5=Music

Icon6NameAndPath=#@#Images\2.png
LocationPath6=shell:RecycleBinFolder
Text6=Recycle Bin

Icon7NameAndPath=#@#Images\3.png
LocationPath7=ms-settings:
Text7=Settings

#If you need icons for your applications then the best website for that is:
#https://www.flaticon.com/






;█▄▄ ▄▀█ ▀█▀ ▀█▀ █▀▀ █▀█ █▄█   █▀ █▀▀ ▀█▀ ▀█▀ █ █▄░█ █▀▀ █▀
;█▄█ █▀█ ░█░ ░█░ ██▄ █▀▄ ░█░   ▄█ ██▄ ░█░ ░█░ █ █░▀█ █▄█ ▄█

BScale=0.9
BColor=255,255,255





;█▀▄▀█ █░█ █▀ █ █▀▀   █▀█ █░░ ▄▀█ █▄█ █▀▀ █▀█   █▀ █▀▀ ▀█▀ ▀█▀ █ █▄░█ █▀▀ █▀
;█░▀░█ █▄█ ▄█ █ █▄▄   █▀▀ █▄▄ █▀█ ░█░ ██▄ █▀▄   ▄█ ██▄ ░█░ ░█░ █ █░▀█ █▄█ ▄█

MScale=2.2
MColor=255,255,255




;█▄░█ █▀▀ █▀▀ █▀▄   █░█ █▀▀ █░░ █▀█ ▀█
;█░▀█ ██▄ ██▄ █▄▀   █▀█ ██▄ █▄▄ █▀▀ ░▄

#Feeling stuck on how to set up the dock or
#The music player is not working?
#Well you should join my simple discord server where
#I as well as others can help you fix it!
#https://discord.com/invite/AfvJzhXJgt







████████╗██╗░░██╗███████╗  ███████╗███╗░░██╗██████╗░
╚══██╔══╝██║░░██║██╔════╝  ██╔════╝████╗░██║██╔══██╗
░░░██║░░░███████║█████╗░░  █████╗░░██╔██╗██║██║░░██║
░░░██║░░░██╔══██║██╔══╝░░  ██╔══╝░░██║╚████║██║░░██║
░░░██║░░░██║░░██║███████╗  ███████╗██║░╚███║██████╔╝
░░░╚═╝░░░╚═╝░░╚═╝╚══════╝  ╚══════╝╚═╝░░╚══╝╚═════╝░


